import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Quicksand } from "next/font/google";
import "./globals.css";

const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-roboto', // define uma variável CSS
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} font-[Gilroy] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
